version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: hft_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=hft_user
      - POSTGRES_DB=hft_data
    ports:
      - "5432:5432"
    volumes:
      - ./timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hft_user -d hft_data"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Добавим удобный UI для просмотра базы (опционально, но полезно)
  pgadmin:
    image: dpage/pgadmin4
    container_name: hft_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - timescaledb